site_name: Citrix Workspace app for HTML5 1808 SDK
site_description: Reference guide for Citrix Workspace app for HTML5 1808 SDK
theme_dir: citrix-sdk
markdown_extensions:
  - admonition
  - codehilite
  - toc:
     anchorlink: True

pages:
- HDX SDK for HTML5: index.md
- SDK Capabilities: capabilities.md
- API Reference:
  - Class:
    - ReceiverError: ReceiverError.md
    - Session: session.md
  - Namespaces:
    - Receiver: citrix-receiver.md
- Events: events.md
- Global: global.md
- SDK Sample: sample.md
